import React,{useState}from'react';
import{Building2,CheckCircle2,MapPin,Plus,Save,ShieldCheck,TrendingUp,Upload}from'lucide-react';
import{PageHead,Status}from'../../components/UI';
import{useToast}from'../../App';
import{centerIdentity}from'./centerStore';

const partnerFields=[['Organization name','Udaan Skills Foundation'],['PAN number','AAACU1234A'],['GST / Udyam number','08AAACU1234A1ZP'],['Authorized person','Anita Sharma'],['Authorized contact','9876543210'],['Company email','operations@udaanskills.org']];
const centerFields=[['Center name',centerIdentity.center],['Center code',centerIdentity.centerCode],['Center type','Private'],['Project name','CSR Skill Employment Program'],['SPOC name','Rajesh Kumar'],['SPOC mobile','9876543200'],['Center email','jaipur@udaanskills.org'],['Website','https://udaanskills.org'],['State','Rajasthan'],['District','Jaipur'],['City / block','Sanganer'],['Full address','Sitapura Industrial Area, Jaipur'],['PIN code','302022'],['Nearest railway station','Sanganer'],['Nearest bus stand','Sitapura'],['Service radius','50 km'],['Sector','Manufacturing, Logistics'],['Accreditations','NSQF, SSC, NSDC']];

export function TrainingPartnerProfile(){return <Setup title="Training partner profile" sub="Legal identity and authorized contact for the organization that manages this center." fields={partnerFields} icon={Building2} documents="PAN, GST/Udyam and authorization documents"/>}
export function CenterProfile(){return <Setup title="Center profile & verification" sub="Identity, location, infrastructure, accreditation and training capability for the assigned center." fields={centerFields} icon={MapPin} documents="Exterior, interior, classroom, lab and accreditation evidence"/>}
function Setup({title,sub,fields,icon:Icon,documents}){const toast=useToast(),[values,setValues]=useState(Object.fromEntries(fields));return <><PageHead kicker="VERIFIED CENTER SETUP" title={title} sub={sub}><button className="btn primary" onClick={()=>{localStorage.setItem(`exo-${title}`,JSON.stringify(values));toast('Verified profile changes saved')}}><Save/>Save changes</button></PageHead><div className="settings-layout"><section className="panel form-detail"><header><div><h3>Verified information</h3><p>Required fields are checked before saving and retained in the activity history.</p></div><Status tone="active">Verified</Status></header><div className="panel-body"><div className="form-grid">{fields.map(([label,value],i)=><label className={`field-label ${['Full address','Accreditations'].includes(label)?'wide':''}`} key={label}>{label} *<input value={values[label]??value} readOnly={label==='Center code'} onChange={e=>setValues({...values,[label]:e.target.value})}/></label>)}</div><label className="document-zone"><Upload/><div><b>{documents}</b><p>Upload clear PDF, JPG or PNG evidence. Existing verified files remain available until replaced.</p></div><span className="btn ghost">Upload files</span><input type="file" multiple hidden/></label></div></section><aside className="panel status-aside"><header><div><h3>Verification status</h3><p>Admin-reviewed master data</p></div></header><div className="panel-body"><div className="setup-icon"><Icon/></div><ul><li><CheckCircle2/>Identity complete</li><li><CheckCircle2/>Assigned center fixed</li><li><CheckCircle2/>Contact verified</li><li><ShieldCheck/>Role and data boundaries active</li></ul></div></aside></div></>}

export function AvailabilityPipeline(){const toast=useToast(),seed=[{sector:'Manufacturing',role:'Machine Operator',count:84,date:'2026-09-30',status:'Confirmed'},{sector:'Logistics',role:'Warehouse Associate',count:56,date:'2026-10-15',status:'Confirmed'},{sector:'Retail',role:'Sales Associate',count:48,date:'2026-10-01',status:'Draft'}],[rows,setRows]=useState(()=>{try{return JSON.parse(localStorage.getItem('exo-center-pipeline'))||seed}catch{return seed}}),[form,setForm]=useState(null);const save=()=>{if(!form.sector||!form.role||!form.count||!form.date){toast('Complete sector, job role, count and availability date');return}const next=[{...form,id:Date.now(),status:'Confirmed'},...rows];setRows(next);localStorage.setItem('exo-center-pipeline',JSON.stringify(next));setForm(null);toast('30-day availability forecast saved')};return <><PageHead kicker="SUPPLY FORECAST" title="30-day availability pipeline" sub="Forecast upcoming supply separately from verified candidate profiles."><button className="btn primary" onClick={()=>setForm({sector:'',role:'',count:'',date:''})}><Plus/>Add forecast</button></PageHead><section className="workspace-card"><div className="pipeline-list">{rows.map((x,i)=><article key={x.id||i}><span><TrendingUp/></span><div><Status tone={x.status.toLowerCase()}>{x.status}</Status><h3>{x.sector} · {x.role}</h3><p>Expected available from {new Date(x.date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</p></div><strong>{x.count}<small>candidates</small></strong></article>)}</div></section>{form&&<div className="inline-editor panel"><header><div><h3>Add supply forecast</h3><p>This does not create candidate records.</p></div></header><div className="panel-body"><div className="form-grid"><F label="Sector" value={form.sector} onChange={v=>setForm({...form,sector:v})}/><F label="Job role" value={form.role} onChange={v=>setForm({...form,role:v})}/><F label="Candidate count" type="number" value={form.count} onChange={v=>setForm({...form,count:v})}/><F label="Available from" type="date" value={form.date} onChange={v=>setForm({...form,date:v})}/></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setForm(null)}>Cancel</button><button className="btn primary" onClick={save}>Save forecast</button></div></div></div>}</>}
function F({label,value,onChange,type='text'}){return <label className="field-label">{label} *<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
