import React,{useMemo,useState}from'react';
import{ArrowLeft,CheckCircle2,Save,ShieldCheck,Upload}from'lucide-react';
import{useNavigate,useSearchParams}from'react-router-dom';
import{useToast}from'../../App';
import{centerIdentity,loadBatches,loadCandidates,nextCandidateId,saveCandidates}from'./centerStore';
import'./center-registration.css';

const empty={firstName:'',lastName:'',whatsapp:'',alternate:'',email:'',gender:'',age:'',state:'Rajasthan',district:'',currentLocation:'',permanentLocation:'',qualification:'',skills:'',experienceType:'Fresher',experience:'',preferredLocation:'',relocate:'No',salary:'',available:'Yes',industry:'',languages:['Hindi'],trainingStatus:'Ongoing',batch:'',batchEnd:'',aadhaar:'',call:true,sms:true,whatsappConsent:true,emailConsent:true,terms:false,privacy:false};
export default function CenterCandidateRegistration(){
  const nav=useNavigate(),toast=useToast(),[params]=useSearchParams(),batches=useMemo(loadBatches,[]),requested=params.get('batch')||'',[data,setData]=useState({...empty,batch:requested,batchEnd:batches.find(b=>b.code===requested)?.endDate||''}),[savedId,setSavedId]=useState('');
  const set=(key,value)=>setData(d=>({...d,[key]:value}));
  const selectBatch=code=>{const b=batches.find(x=>x.code===code);setData(d=>({...d,batch:code,batchEnd:b?.endDate||''}))};
  const save=()=>{const required=['firstName','lastName','whatsapp','gender','age','district','currentLocation','permanentLocation','qualification','skills','preferredLocation','salary','industry','batch'];if(required.some(k=>!data[k])){toast('Complete every required candidate field');return}if(!batches.some(b=>b.code===data.batch)){toast('Select an existing actual batch');return}if(!data.terms||!data.privacy){toast('Candidate consent and Privacy acceptance are required');return}const existing=loadCandidates(),id=nextCandidateId(existing),record={...data,id,partner:centerIdentity.partner,center:centerIdentity.center,centerCode:centerIdentity.centerCode,source:'center-assisted',consent:true,consentVersion:'1.0',consentAt:new Date().toISOString(),createdAt:new Date().toISOString(),profile:100};saveCandidates([record,...existing]);setSavedId(id)};
  if(savedId)return <div className="reg-success"><div><CheckCircle2/><span>CANDIDATE CREATED</span><h1>{data.firstName} {data.lastName} is registered.</h1><p>The profile is linked to {data.batch} at {centerIdentity.center}.</p><strong>{savedId}</strong><button className="btn primary" onClick={()=>nav('/center/candidates')}>View candidate list</button></div></div>;
  return <div className="center-registration"><div className="center-registration-head"><button className="btn ghost" onClick={()=>nav('/center/candidates')}><ArrowLeft/>Back to candidates</button><div><span>CENTER-ASSISTED REGISTRATION</span><h1>Add candidate</h1><p>All required profile, employability, batch and consent details from the onboarding specification.</p></div><button className="btn primary" onClick={save}><Save/>Create candidate</button></div>
    <div className="registration-scope"><CheckCircle2/><span><b>{centerIdentity.center}</b><small>{centerIdentity.centerCode} · Training partner: {centerIdentity.partner} · fixed from login</small></span></div>
    <section className="registration-section"><header><span>01</span><div><h2>Personal & contact details</h2><p>Identity and WhatsApp-active communication details.</p></div></header><div className="form-grid"><F label="First name" value={data.firstName} set={v=>set('firstName',v)}/><F label="Last name" value={data.lastName} set={v=>set('lastName',v)}/><F label="WhatsApp-active mobile" value={data.whatsapp} set={v=>set('whatsapp',v)}/><F label="Calling / alternate mobile" value={data.alternate} set={v=>set('alternate',v)} optional/><F label="Email address" type="email" value={data.email} set={v=>set('email',v)} optional/><S label="Gender" value={data.gender} set={v=>set('gender',v)} options={['','Female','Male','Other','Prefer not to say']}/><F label="Age in completed years" type="number" value={data.age} set={v=>set('age',v)}/><S label="Highest qualification" value={data.qualification} set={v=>set('qualification',v)} options={['','8th pass','10th pass','12th pass','ITI','Diploma','Graduate','Postgraduate']}/></div></section>
    <section className="registration-section"><header><span>02</span><div><h2>Location & employability</h2><p>Used for skill matching, mobility and job suitability.</p></div></header><div className="form-grid"><F label="State" value={data.state} set={v=>set('state',v)}/><F label="District" value={data.district} set={v=>set('district',v)}/><F label="Current location / city or block" value={data.currentLocation} set={v=>set('currentLocation',v)}/><F label="Permanent location" value={data.permanentLocation} set={v=>set('permanentLocation',v)}/><label className="field-label wide">Specific skills *<textarea rows="3" value={data.skills} onChange={e=>set('skills',e.target.value)} placeholder="Machine operation, 5S, basic computer…"/></label><S label="Experience level" value={data.experienceType} set={v=>set('experienceType',v)} options={['Fresher','Experienced']}/>{data.experienceType==='Experienced'&&<F label="Experience details" value={data.experience} set={v=>set('experience',v)}/>}<F label="Preferred job location" value={data.preferredLocation} set={v=>set('preferredLocation',v)}/><S label="Willing to relocate" value={data.relocate} set={v=>set('relocate',v)} options={['No','Yes - within district','Yes - within state','Yes - anywhere in India']}/><F label="Expected monthly salary" value={data.salary} set={v=>set('salary',v)}/><S label="Available / interested for job" value={data.available} set={v=>set('available',v)} options={['Yes','No','Available after training']}/><S label="Preferred industry" value={data.industry} set={v=>set('industry',v)} options={['','Manufacturing','Logistics','Retail','Automotive','IT-ITES','Hospitality']}/><div className="field-label wide">Languages known *<div className="check-row">{['Hindi','English','Rajasthani','Other'].map(x=><label key={x}><input type="checkbox" checked={data.languages.includes(x)} onChange={e=>set('languages',e.target.checked?[...data.languages,x]:data.languages.filter(y=>y!==x))}/>{x}</label>)}</div></div></div></section>
    <section className="registration-section"><header><span>03</span><div><h2>Training & documents</h2><p>The candidate must be linked to an actual batch created by this center.</p></div></header><div className="form-grid"><S label="Training status" value={data.trainingStatus} set={v=>set('trainingStatus',v)} options={['Ongoing','Completed']}/><label className="field-label">Actual batch code *<select value={data.batch} onChange={e=>selectBatch(e.target.value)}><option value="">Select an existing batch</option>{batches.map(b=><option key={b.id} value={b.code}>{b.code} · {b.jobRole} · ends {b.endDate}</option>)}</select></label><F label="Batch end date" type="date" value={data.batchEnd} set={()=>{}} readOnly/><F label="Aadhaar number" value={data.aadhaar} set={v=>set('aadhaar',v)} optional hint="Optional; masked and restricted after saving"/><label className="file-box"><Upload/><div><b>Resume</b><small>PDF or DOCX · maximum 5 MB</small></div><span>Browse file</span><input type="file" accept=".pdf,.doc,.docx"/></label><label className="file-box"><Upload/><div><b>Qualification / training certificate</b><small>Optional PDF, JPG or PNG</small></div><span>Browse file</span><input type="file" accept=".pdf,.jpg,.jpeg,.png"/></label></div></section>
    <section className="registration-section"><header><span>04</span><div><h2>Consent & communication</h2><p>Store source, timestamp, notice version and selected channels.</p></div></header><div className="consent-grid">{[['call','Phone calls'],['sms','SMS alerts'],['whatsappConsent','WhatsApp messages'],['emailConsent','Email updates']].map(([k,l])=><label key={k}><input type="checkbox" checked={data[k]} onChange={e=>set(k,e.target.checked)}/><span><b>{l}</b><small>Job, interview and employment updates</small></span></label>)}</div><label className="legal-check"><input type="checkbox" checked={data.terms} onChange={e=>set('terms',e.target.checked)}/><span>Candidate agrees to the Terms & Conditions and processing for candidate-job matching and recruitment evaluation.</span></label><label className="legal-check"><input type="checkbox" checked={data.privacy} onChange={e=>set('privacy',e.target.checked)}/><span>Candidate accepts the Privacy Policy and understands consent can be withdrawn.</span></label><div className="consent-proof"><ShieldCheck/><p>Consent evidence will store notice version 1.0, timestamp, center-assisted source and selected channels.</p></div></section>
    <div className="registration-actions"><button className="btn ghost" onClick={()=>nav('/center/candidates')}>Cancel</button><button className="btn primary" onClick={save}><Save/>Create candidate profile</button></div>
  </div>;
}
function F({label,value,set,type='text',optional=false,hint,readOnly=false}){return <label className="field-label">{label}{!optional&&' *'}<input type={type} value={value} readOnly={readOnly} onChange={e=>set(e.target.value)}/>{hint&&<small>{hint}</small>}</label>}
function S({label,value,set,options}){return <label className="field-label">{label} *<select value={value} onChange={e=>set(e.target.value)}>{options.map((x,i)=><option key={x||i} value={x}>{x||`Select ${label.toLowerCase()}`}</option>)}</select></label>}
