import React,{useMemo,useState}from'react';
import{useNavigate}from'react-router-dom';
import{CheckCircle2,Clock3,Download,FileWarning,Plus,Search,ShieldCheck,UserRound,Users}from'lucide-react';
import{Modal,PageHead,Status}from'../../components/UI';
import{candidateReadiness,loadBatches,loadCandidates}from'./centerStore';

export default function CenterCandidates(){
  const nav=useNavigate(),[candidates]=useState(loadCandidates),[batches]=useState(loadBatches),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[detail,setDetail]=useState(null);
  const rows=useMemo(()=>candidates.filter(c=>{const readiness=candidateReadiness(c);return(filter==='All'||readiness===filter)&&[c.id,c.firstName,c.lastName,c.whatsapp,c.batch,c.skills,c.industry].join(' ').toLowerCase().includes(query.toLowerCase())}),[candidates,query,filter]);
  const jobReady=candidates.filter(c=>candidateReadiness(c)==='Job ready').length,ending=candidates.filter(c=>candidateReadiness(c)==='Eligible soon').length,incomplete=candidates.filter(c=>(c.profile||0)<80||!c.consent).length;
  const exportRows=()=>{const csv=['Candidate ID,Name,Mobile,Batch,Training status,Availability,Readiness',...candidates.map(c=>[c.id,`${c.firstName} ${c.lastName}`,c.whatsapp,c.batch,c.trainingStatus,c.available,candidateReadiness(c)].map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='center-candidates.csv';a.click();URL.revokeObjectURL(a.href)};
  return <>
    <PageHead kicker="CANDIDATE OPERATIONS" title="Center candidates" sub="Register complete candidate profiles, link each learner to an actual batch and track placement readiness.">
      <button className="btn ghost" onClick={exportRows}><Download/>Export</button><button className="btn primary" onClick={()=>nav('/center/candidates/new')}><Plus/>Register candidate</button>
    </PageHead>
    <div className="workspace-stats"><article><Users/><span>Total candidates<b>{candidates.length}</b></span></article><article><CheckCircle2/><span>Job ready<b>{jobReady}</b></span></article><article><Clock3/><span>Eligible soon<b>{ending}</b></span></article><article><FileWarning/><span>Profiles needing action<b>{incomplete}</b></span></article></div>
    <section className="workspace-card"><div className="candidate-tabs">{['All','In training','Eligible soon','Job ready','Not available'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="workspace-toolbar"><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, EXOWORK ID, mobile, skill or batch…"/></div><button className="btn ghost" onClick={()=>nav('/center/batches')}>Manage batches</button></div>
      <div className="candidate-table table-scroll"><table><thead><tr><th>Candidate</th><th>Contact & location</th><th>Training batch</th><th>Profile</th><th>Placement readiness</th></tr></thead><tbody>{rows.map(c=>{const batch=batches.find(b=>b.code===c.batch),readiness=candidateReadiness(c);return <tr key={c.id} onClick={()=>setDetail(c)}><td><div className="candidate-name"><span>{c.firstName?.[0]}{c.lastName?.[0]}</span><div><b>{c.firstName} {c.lastName}</b><small>{c.id}</small></div></div></td><td><b>{mask(c.whatsapp)}</b><small>{c.district||'Location incomplete'} · {c.qualification||'Qualification incomplete'}</small></td><td><b>{c.batch||'No batch assigned'}</b><small>{batch?`${batch.jobRole} · ends ${formatDate(batch.endDate)}`:'Candidate requires a valid existing batch'}</small></td><td><b>{c.profile||calculateProfile(c)}%</b><div className="mini-progress"><i style={{width:`${c.profile||calculateProfile(c)}%`}}/></div><small>{c.consent?'Consent active':'Consent missing'}</small></td><td><Status tone={readiness.toLowerCase().replaceAll(' ','-')}>{readiness}</Status><small>{c.available}</small></td></tr>})}</tbody></table>{!rows.length&&<div className="workspace-empty">No candidates match this view.</div>}</div>
    </section>
    <Modal open={!!detail} onClose={()=>setDetail(null)} title={detail?`${detail.firstName} ${detail.lastName}`:''} sub={detail?.id}>{detail&&<CandidateDetail candidate={detail} batch={batches.find(b=>b.code===detail.batch)}/>}</Modal>
  </>;
}
function CandidateDetail({candidate:c,batch}){return <><div className="candidate-detail-head"><span><UserRound/></span><div><Status tone={candidateReadiness(c).toLowerCase().replaceAll(' ','-')}>{candidateReadiness(c)}</Status><h3>{c.firstName} {c.lastName}</h3><p>{mask(c.whatsapp)} · {c.email||'No email'} · {c.district||'Location incomplete'}</p></div></div><div className="detail-sections"><section><h4>Personal & employability</h4><Info label="Qualification" value={c.qualification}/><Info label="Skills" value={c.skills}/><Info label="Experience" value={c.experienceType==='Experienced'?c.experience:'Fresher'}/><Info label="Preferred industry" value={c.industry}/><Info label="Expected salary" value={c.salary?`₹${c.salary}`:''}/><Info label="Relocation" value={c.relocate}/></section><section><h4>Training & readiness</h4><Info label="Actual batch" value={c.batch}/><Info label="Job role" value={batch?.jobRole}/><Info label="Trainer" value={batch?.trainer}/><Info label="Batch end" value={formatDate(c.batchEnd||batch?.endDate)}/><Info label="Training status" value={c.trainingStatus}/><Info label="Available for job" value={c.available}/></section></div><div className="consent-banner"><ShieldCheck/><div><b>Consent evidence {c.consent?'recorded':'missing'}</b><p>Registration source, timestamp, notice version and channel preferences are retained with the candidate record.</p></div></div></>}
function Info({label,value}){return <div className="info-row"><span>{label}</span><b>{value||'Not provided'}</b></div>}
function mask(v=''){return v.length>=4?`${v.slice(0,2)}••• ••${v.slice(-3)}`:v||'No mobile'}
function formatDate(value){return value?new Date(value+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Not available'}
function calculateProfile(c){const fields=['firstName','lastName','whatsapp','district','qualification','skills','industry','salary','batch','batchEnd'];return Math.round(fields.filter(k=>c[k]).length/fields.length*100)}
