export const candidates=[
{id:'EXO-CAN-102548',name:'Neha Kumari',phone:'98••• ••548',center:'ABC Skill Development Center',batch:'MAN-26-08',role:'Machine Operator',location:'Jaipur',status:'Available',profile:92,interest:'Interested',consent:'Active',updated:'12 min ago'},
{id:'EXO-CAN-102547',name:'Rahul Meena',phone:'97••• ••214',center:'Govt. ITI Ajmer',batch:'LOG-26-07',role:'Warehouse Associate',location:'Ajmer',status:'Interview',profile:86,interest:'Interested',consent:'Active',updated:'28 min ago'},
{id:'EXO-CAN-102531',name:'Farhan Khan',phone:'99••• ••882',center:'ABC Skill Development Center',batch:'CNC-26-07',role:'CNC Operator',location:'Jaipur',status:'Job Ready',profile:78,interest:'No response',consent:'Active',updated:'1 hr ago'},
{id:'EXO-CAN-102490',name:'Pooja Saini',phone:'96••• ••019',center:'Udaan Skills Tonk',batch:'RTL-26-06',role:'Retail Associate',location:'Tonk',status:'Joining Pending',profile:94,interest:'Interested',consent:'Active',updated:'2 hrs ago'},
{id:'EXO-CAN-102462',name:'Vikas Gurjar',phone:'95••• ••634',center:'Govt. ITI Dausa',batch:'ELC-26-05',role:'Electrician',location:'Dausa',status:'Joined',profile:88,interest:'Interested',consent:'Active',updated:'Yesterday'},
{id:'EXO-CAN-102418',name:'Rina Yadav',phone:'94••• ••721',center:'ABC Skill Development Center',batch:'MAN-26-08',role:'Machine Operator',location:'Jaipur',status:'Selected',profile:90,interest:'Interested',consent:'Active',updated:'Yesterday'}];
export const jobs=[{id:'JOB-26091',title:'Machine Operator',company:'Astro Components',location:'Sitapura, Jaipur',openings:12,matches:42,stage:'Active',salary:'₹14k–18k',deadline:'30 Sep'},{id:'JOB-26086',title:'Warehouse Associate',company:'BlueRoute Logistics',location:'Ajmer Road, Jaipur',openings:20,matches:28,stage:'Matching',salary:'₹13k–16k',deadline:'25 Sep'},{id:'JOB-26072',title:'Retail Sales Executive',company:'Nova Retail India',location:'Jaipur',openings:8,matches:19,stage:'Interviewing',salary:'₹15k + incentive',deadline:'22 Sep'},{id:'JOB-26064',title:'CNC Trainee',company:'Prism Auto Systems',location:'VKI, Jaipur',openings:6,matches:16,stage:'Draft',salary:'₹16k–20k',deadline:'28 Sep'}];
export const centers=[{name:'ABC Skill Development Center',code:'EXO-CTR-0086',city:'Jaipur',type:'Private',candidates:1250,available:210,joined:13,status:'Verified'},{name:'Government ITI Ajmer',code:'EXO-CTR-0062',city:'Ajmer',type:'ITI',candidates:816,available:184,joined:18,status:'Verified'},{name:'Udaan Skills Tonk',code:'EXO-CTR-0114',city:'Tonk',type:'NGO',candidates:426,available:88,joined:9,status:'Pending'}];
