import React,{useState}from'react';
import{useNavigate,useOutletContext}from'react-router-dom';
import{BriefcaseBusiness,Building2,CalendarDays,FileText,ShieldCheck,ArrowRight,MapPin,IndianRupee,PlayCircle,Clock3,CheckCircle2,Sparkles,UserRound,UsersRound,Phone,GraduationCap}from'lucide-react';
import{Panel,Status}from'../../components/UI';

const jobs=[['Machine Operator','Jaipur, Rajasthan','₹14,000 – ₹18,000','86%'],['CNC Trainee','VKI, Jaipur','₹16,000 – ₹20,000','82%'],['Quality Inspector','Sitapura, Jaipur','₹15,000 – ₹19,000','78%']];

export default function CandidateDashboard(){
  const nav=useNavigate();
  const {candidateProfile}=useOutletContext()||{};
  const candidateName=candidateProfile?.first_name||'Candidate';
  const candidateCode=candidateProfile?.candidate_code;
  const[mode,setMode]=useState('partner');
  const partnered=mode==='partner';
  const journey=partnered?[['Profile ready','Verified by partner',CheckCircle2,'done'],['Jobs matched','6 opportunities',Sparkles,'done'],['Interview','Tomorrow · 11:30',CalendarDays,'current'],['Joining','Partner will assist',UsersRound,'']]:[['Profile ready','Completed by you',CheckCircle2,'done'],['Jobs matched','6 opportunities',Sparkles,'done'],['Interview','Tomorrow · 11:30',CalendarDays,'current'],['Joining','Track it here',BriefcaseBusiness,'']];
  return <div className="candidate-dashboard">
    <section className="candidate-mode-card" aria-label="Dashboard preview mode"><div><span>VIEWING AS</span><h3>{partnered?'Training partner enrolled':'Independent candidate'}</h3><p>{partnered?'Your training partner supports your profile, interview and joining journey.':'You manage your profile, applications and employment journey directly.'}</p></div><div className="candidate-mode-toggle" role="group" aria-label="Choose candidate type"><button className={partnered?'active':''} onClick={()=>setMode('partner')}><Building2/>Training partner enrolled</button><button className={!partnered?'active':''} onClick={()=>setMode('independent')}><UserRound/>Independent</button></div></section>
    <section className="candidate-welcome"><div className="candidate-avatar">{candidateProfile?.initials||candidateName.slice(0,2).toLocaleUpperCase()}</div><div><span>WELCOME BACK, {candidateName.toLocaleUpperCase()}</span><h1>{partnered?'Your placement journey is moving forward.':'Your next opportunity is taking shape.'}</h1><p>{candidateCode&&<>Profile {candidateCode} </>}{partnered?'Enrolled through ABC Skill Development Center':'Self-managed profile'}</p></div><div className="profile-completion"><b>92%</b><span>Profile ready</span><i><em/></i></div></section>
    {partnered&&<section className="partner-relationship"><div className="partner-mark"><Building2/></div><div><span>YOUR TRAINING & PLACEMENT PARTNER</span><h2>ABC Skill Development Center</h2><p>Batch MAN-26-08 · Machine Operator · Training ends 30 Sep 2026</p></div><div className="partner-support"><span><CheckCircle2/> Profile verified</span><span><UsersRound/> Placement support active</span></div><button onClick={()=>nav('/candidate/profile')}>View training details <ArrowRight/></button></section>}
    {!partnered&&<section className="independent-note"><UserRound/><div><b>You are managing this journey independently</b><p>Keep your profile and availability current so EXOWORK can improve your matches. You can connect a training partner later if one invites you.</p></div><button onClick={()=>nav('/candidate/profile')}>Update profile <ArrowRight/></button></section>}
    <div className="journey-track">{journey.map(([t,s,I,c],i)=><div className={c} key={t}><span><I/></span><div><b>{t}</b><small>{s}</small></div>{i<3&&<i/>}</div>)}</div>
    <div className="candidate-alert"><CalendarDays/><div><span>TOMORROW · 11:30 AM</span><h2>Your interview is confirmed</h2><p>Machine Operator · Astro Components · Sitapura, Jaipur{partnered?' · Your coordinator has been notified':''}</p></div><button onClick={()=>nav('/candidate/interviews')}>View interview details <ArrowRight/></button></div>
    <div className="candidate-grid"><main><Panel title="Opportunities selected for you" sub="Matched to your skills, location and availability" action={<button className="text-link" onClick={()=>nav('/candidate/opportunities')}>View all <ArrowRight/></button>}><div className="candidate-jobs">{jobs.map((x,i)=><article key={x[0]}><div><Status tone={i===0?'active':'matching'}>{i===0?'Best match':'Recommended'}</Status><b>{x[3]} match</b></div><h3>{x[0]}</h3><p>Verified employer · Company revealed after interview confirmation</p><span><MapPin/>{x[1]}</span><span><IndianRupee/>{x[2]}</span><button onClick={()=>nav('/candidate/interests')}>{i===0?'I am interested':'View opportunity'} <ArrowRight/></button></article>)}</div></Panel></main><aside>
      {partnered&&<Panel title="Partner support" sub="People helping with your placement"><div className="partner-contact"><span>PS</span><div><b>Priya Sharma</b><small>Placement coordinator</small><a href="tel:+919800000000"><Phone/> Contact coordinator</a></div></div><div className="support-list"><span><GraduationCap/> Training record connected</span><span><CalendarDays/> Interview follow-up enabled</span><span><BriefcaseBusiness/> Joining support included</span></div></Panel>}
      <Panel title="Profile readiness" sub={partnered?'Verified with your training record':'You are eligible for job matching'}><div className="candidate-checklist">{[['Personal information','Complete',true],[partnered?'Skills & training':'Skills & experience','Complete',true],['Resume','Generated',true],['Communication consent','4 channels active',true],['Aadhaar','Optional · not added',false]].map(x=><div key={x[0]}><span className={x[2]?'ok':''}>{x[2]?<CheckCircle2/>:<Clock3/>}</span><div><b>{x[0]}</b><small>{x[1]}</small></div></div>)}</div><button className="btn ghost block" onClick={()=>nav('/candidate/profile')}>Review my profile</button></Panel>
      <Panel title="Career preparation"><div className="video-card"><span><PlayCircle/></span><div><b>Prepare for your interview</b><small>Hindi · 6 minutes</small></div><button onClick={()=>nav('/candidate/interviews')}>Watch</button></div><div className="video-card"><span><FileText/></span><div><b>Your EXOWORK resume</b><small>Updated 12 Sep</small></div><button onClick={()=>nav('/candidate/resume')}>Open</button></div></Panel>
      <Panel title="Your privacy"><div className="privacy-mini"><ShieldCheck/><p>{partnered?'Your partner can access only the training and placement information needed to support your journey.':'Your details are shared only with verified employers through authorized hiring workflows.'}</p></div><button className="text-link" onClick={()=>nav('/candidate/consent')}>Manage consent <ArrowRight/></button></Panel>
    </aside></div>
  </div>;
}
