import React,{useEffect,useState}from'react';
import axios from'axios';
import{Link,useNavigate}from'react-router-dom';
import{ArrowLeft,ArrowRight,BriefcaseBusiness,CheckCircle2,GraduationCap,MapPin,Save,ShieldCheck,Upload,UserRound}from'lucide-react';
import BrandLogo from'../../components/BrandLogo.jsx';
import{useToast}from'../../App';

const steps=[['Account',UserRound],['Personal',UserRound],['Location',MapPin],['Employability',BriefcaseBusiness],['Training & files',GraduationCap],['Consent & review',ShieldCheck]];
const empty={firstName:'',lastName:'',whatsapp:'',alternate:'',email:'',password:'',passwordConfirmation:'',gender:'',age:'',qualification:'',state:'Rajasthan',district:'',currentLocation:'',permanentLocation:'',preferredLocations:'',relocation:'No',skills:'',experienceType:'Fresher',experienceDetails:'',salary:'',availability:'Yes',industry:'',languages:['Hindi'],trainingStatus:'Not enrolled',trainingPartner:'',trainingCenter:'',batchCode:'',batchEndDate:'',aadhaar:'',locationConsent:false,photoConsent:true,callConsent:true,smsConsent:true,whatsappConsent:true,emailConsent:true,terms:false,privacy:false};
const required=[['whatsapp','password','passwordConfirmation'],['firstName','lastName','gender','age','qualification'],['state','district','currentLocation','permanentLocation','preferredLocations'],['skills','salary','availability','industry','languages'],[],['terms','privacy']];
const labels={whatsapp:'WhatsApp mobile',password:'Password',passwordConfirmation:'Password confirmation',firstName:'First name',lastName:'Last name',gender:'Gender',age:'Age',qualification:'Qualification',state:'State',district:'District',currentLocation:'Current location',permanentLocation:'Permanent location',preferredLocations:'Preferred job location',skills:'Skills',salary:'Expected salary',availability:'Availability',industry:'Preferred industry',languages:'Languages',terms:'Terms acceptance',privacy:'Privacy acceptance'};
const serverKeys={first_name:'firstName',last_name:'lastName',alternate_mobile:'alternate',password_confirmation:'passwordConfirmation',current_location:'currentLocation',permanent_location:'permanentLocation',preferred_locations:'preferredLocations',relocation_preference:'relocation',experience_type:'experienceType',experience_details:'experienceDetails',expected_monthly_salary:'salary',preferred_industry:'industry',training_status:'trainingStatus',training_partner:'trainingPartner',training_center:'trainingCenter',batch_code:'batchCode',batch_end_date:'batchEndDate',aadhaar_number:'aadhaar',terms_accepted:'terms',privacy_accepted:'privacy'};
const stepFor={whatsapp:0,email:0,password:0,passwordConfirmation:0,firstName:1,lastName:1,gender:1,age:1,qualification:1,state:2,district:2,currentLocation:2,permanentLocation:2,preferredLocations:2,relocation:2,skills:3,experienceType:3,experienceDetails:3,salary:3,availability:3,industry:3,languages:3,trainingStatus:4,trainingPartner:4,trainingCenter:4,batchCode:4,batchEndDate:4,aadhaar:4,terms:5,privacy:5};
const draftTokenKey='exo-candidate-draft-token';
const safeDraft=data=>{const{password,passwordConfirmation,aadhaar,terms,privacy,...safe}=data;return safe};

export default function CandidateRegistration({mode='public'}){
  const nav=useNavigate(),toast=useToast();
  const preview=new URLSearchParams(window.location.search).get('test')==='1';
  const[step,setStep]=useState(0),[data,setData]=useState(empty),[files,setFiles]=useState({}),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),[savingDraft,setSavingDraft]=useState(false),[savedAt,setSavedAt]=useState(''),[result,setResult]=useState(null),[message,setMessage]=useState('');
  useEffect(()=>{if(preview)return;const token=localStorage.getItem(draftTokenKey);if(!token)return;axios.get(`/api/candidate-drafts/${token}`).then(({data:response})=>{setData(current=>({...current,...response.draft.data,password:'',passwordConfirmation:'',aadhaar:'',terms:false,privacy:false}));setStep(0);setSavedAt(response.draft.saved_at);toast('Draft restored — re-enter your password to continue securely')}).catch(()=>localStorage.removeItem(draftTokenKey))},[]);
  const set=(key,value)=>{setData(d=>({...d,[key]:value}));setErrors(e=>({...e,[key]:undefined}));setMessage('')};
  const validate=()=>{const next={};required[step].forEach(key=>{if(!data[key]||(Array.isArray(data[key])&&!data[key].length))next[key]=[`${labels[key]} is required.`]});if(step===0&&data.whatsapp&&!/^\d{10}$/.test(data.whatsapp.replace(/\D/g,'')))next.whatsapp=['Enter a valid 10-digit mobile number.'];if(step===0&&data.password.length<8)next.password=['Use at least 8 characters.'];if(step===0&&data.password!==data.passwordConfirmation)next.passwordConfirmation=['Passwords do not match.'];if(step===4&&data.trainingStatus!=='Not enrolled'){['trainingPartner','trainingCenter','batchCode','batchEndDate'].forEach(key=>{if(!data[key])next[key]=[`${labels[key]||key} is required.`]})}setErrors(next);return !Object.keys(next).length};
  const advance=()=>{if(validate())setStep(x=>x+1)};
  const saveDraft=async()=>{setSavingDraft(true);setMessage('');try{const token=localStorage.getItem(draftTokenKey);const response=await axios.post('/api/candidate-drafts',{token,last_step:step,registration_source:mode,data:safeDraft(data)});localStorage.setItem(draftTokenKey,response.data.draft.token);setSavedAt(response.data.draft.saved_at);toast('Draft saved securely for 30 days')}catch(error){setMessage(error.response?.data?.message||'Draft could not be saved. Please try again.')}finally{setSavingDraft(false)}};
  const submit=async()=>{if(!validate())return;setBusy(true);setMessage('');const form=new FormData();const payload={first_name:data.firstName,last_name:data.lastName,whatsapp:data.whatsapp,alternate_mobile:data.alternate,email:data.email,password:data.password,password_confirmation:data.passwordConfirmation,gender:data.gender,age:data.age,qualification:data.qualification,state:data.state,district:data.district,current_location:data.currentLocation,permanent_location:data.permanentLocation,preferred_locations:data.preferredLocations.split(';').map(x=>x.trim()).filter(Boolean),relocation_preference:data.relocation,skills:data.skills,experience_type:data.experienceType,experience_details:data.experienceDetails,expected_monthly_salary:String(data.salary).replace(/\D/g,''),availability:data.availability,preferred_industry:data.industry,languages:data.languages,training_status:data.trainingStatus,training_partner:data.trainingPartner,training_center:data.trainingCenter,batch_code:data.batchCode,batch_end_date:data.batchEndDate,aadhaar_number:data.aadhaar,location_consent:Number(data.locationConsent),photo_consent:Number(data.photoConsent),call_consent:Number(data.callConsent),sms_consent:Number(data.smsConsent),whatsapp_consent:Number(data.whatsappConsent),email_consent:Number(data.emailConsent),terms_accepted:Number(data.terms),privacy_accepted:Number(data.privacy),registration_source:mode,draft_token:localStorage.getItem(draftTokenKey)||''};Object.entries(payload).forEach(([key,value])=>Array.isArray(value)?value.forEach(v=>form.append(`${key}[]`,v)):form.append(key,value??''));Object.entries(files).forEach(([key,value])=>value&&form.append(key,value));try{const response=await axios.post('/api/candidates',form);localStorage.removeItem(draftTokenKey);setResult(response.data.candidate)}catch(error){const raw=error.response?.data?.errors||{},mapped={};Object.entries(raw).forEach(([key,value])=>mapped[serverKeys[key]||key]=value);setErrors(mapped);setMessage(error.response?.data?.message||'Registration could not be completed. Please try again.');const first=Object.keys(mapped)[0];if(first&&stepFor[first]!==undefined)setStep(stepFor[first])}finally{setBusy(false)}};
  const successCandidate=result||(preview?{first_name:'Shubham',candidate_code:'EXO-CAN-PREVIEW'}:null);
  if(successCandidate)return <main className="reg-success"><section className="success-card">
    <img className="success-confetti-overlay" src="/success-confetti.svg" alt="" aria-hidden="true"/>
    <div className="success-check-wrap"><span className="success-check-halo"/><span className="success-check-icon"><CheckCircle2/></span><i className="success-spark success-spark-one"/><i className="success-spark success-spark-two"/><i className="success-spark success-spark-three"/></div>
    <span className="success-label">REGISTRATION COMPLETE</span>
    <h1>Welcome to EXOWORK,<br/>{successCandidate.first_name}.</h1>
    <p className="success-message">Your profile is ready. Explore roles that match your skills and preferences, and take a look at what comes next.</p>
    <div className="success-id"><span>YOUR EXO ID</span><strong>{successCandidate.candidate_code}</strong></div>
    <button className="success-cta" onClick={()=>nav(mode==='public'?'/candidate/dashboard':'/admin/candidates')}>{mode==='public'?'Explore my dashboard':'Continue to candidate list'}<ArrowRight/></button>
    <p className="success-secure"><ShieldCheck/>Your information is stored securely.</p>
  </section></main>;
  return <div className={'candidate-register '+(mode==='public'?'public-reg':'embedded-reg')}>
    <header className="reg-top"><Link to={mode==='public'?'/':'/admin/candidates'}><ArrowLeft/>Exit registration</Link><div className="reg-brand"><BrandLogo/></div><div className="draft-status">{savedAt&&<small>Saved {new Date(savedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>}<button type="button" className="btn ghost reg-draft-top" disabled={savingDraft} onClick={saveDraft}><Save/>{savingDraft?'Saving…':'Save draft'}</button></div></header>
    <main><aside className="reg-aside"><span className="reg-kicker">{mode==='public'?'CANDIDATE REGISTRATION':'ADMIN ENTRY'}</span><h1>Create your work profile.</h1><p>Add your details to find suitable opportunities.</p><div className="reg-progress"><div><b>{Math.round((step+1)/steps.length*100)}%</b><span>Profile setup</span></div><i><em style={{width:`${Math.round((step+1)/steps.length*100)}%`}}/></i></div><nav>{steps.map(([name,Icon],index)=><button type="button" key={name} className={index<step?'done':index===step?'active':''} onClick={()=>index<step&&setStep(index)}><span>{index<step?<CheckCircle2/>:<Icon/>}</span><div><b>{name}</b><small>{index<step?'Completed':index===step?'In progress':'Next step'}</small></div></button>)}</nav><div className="privacy-note"><ShieldCheck/><p>Your profile is shared only through authorized hiring workflows.</p></div></aside>
      <section className="reg-form"><div className="reg-form-head"><span>STEP {step+1} OF {steps.length}</span><h2>{steps[step][0]}</h2><p>{['Create secure access using your WhatsApp-active mobile.','Add identity and optional profile details.','Set address and job-location preferences.','Describe skills, experience and work preferences.','Connect training details and protected documents.','Choose communication channels and review.'][step]}</p></div>
        {step===0&&<div className="reg-fields"><Field name="whatsapp" label="WhatsApp-active mobile" value={data.whatsapp} set={set} error={errors.whatsapp}/><Field name="email" label="Email address" type="email" value={data.email} set={set} error={errors.email} optional/><Field name="password" label="Create password" type="password" value={data.password} set={set} error={errors.password}/><Field name="passwordConfirmation" label="Confirm password" type="password" value={data.passwordConfirmation} set={set} error={errors.passwordConfirmation}/></div>}
        {step===1&&<div className="reg-fields"><Field name="firstName" label="First name" value={data.firstName} set={set} error={errors.firstName}/><Field name="lastName" label="Last name" value={data.lastName} set={set} error={errors.lastName}/><Field name="alternate" label="Calling / alternate mobile" value={data.alternate} set={set} optional/><Select name="gender" label="Gender" value={data.gender} set={set} error={errors.gender} options={['','Female','Male','Other','Prefer not to say']}/><Field name="age" label="Age in completed years" type="number" value={data.age} set={set} error={errors.age}/><Select name="qualification" label="Highest qualification" value={data.qualification} set={set} error={errors.qualification} options={['','8th pass','10th pass','12th pass','ITI','Diploma','Graduate','Postgraduate']}/><File name="photo" label="Profile photograph" accept="image/jpeg,image/png,image/webp" setFiles={setFiles} hint="JPG, PNG or WebP · maximum 3 MB"/></div>}
        {step===2&&<div className="reg-fields"><Select name="state" label="State" value={data.state} set={set} options={['Rajasthan','Delhi','Haryana','Uttar Pradesh']}/><Field name="district" label="District" value={data.district} set={set} error={errors.district}/><Field name="currentLocation" label="Current location / city or block" value={data.currentLocation} set={set} error={errors.currentLocation}/><Field name="permanentLocation" label="Permanent location" value={data.permanentLocation} set={set} error={errors.permanentLocation}/><Field name="preferredLocations" label="Preferred job locations" value={data.preferredLocations} set={set} error={errors.preferredLocations} wide hint="Separate multiple locations with a semicolon"/><Select name="relocation" label="Willing to relocate?" value={data.relocation} set={set} options={['No','Yes - within district','Yes - within state','Yes - anywhere in India']}/><Toggle label="Use current location for recommendations" checked={data.locationConsent} onChange={v=>set('locationConsent',v)}/></div>}
        {step===3&&<div className="reg-fields"><Field name="skills" label="Specific skills" value={data.skills} set={set} error={errors.skills} wide textarea/><Select name="experienceType" label="Experience level" value={data.experienceType} set={set} options={['Fresher','Experienced']}/>{data.experienceType==='Experienced'&&<Field name="experienceDetails" label="Experience details" value={data.experienceDetails} set={set} error={errors.experienceDetails}/>}<Field name="salary" label="Expected monthly salary" type="number" value={data.salary} set={set} error={errors.salary}/><Select name="availability" label="Available / interested for job?" value={data.availability} set={set} options={['Yes','No','Available after training']}/><Select name="industry" label="Preferred industry" value={data.industry} set={set} error={errors.industry} options={['','Manufacturing','Logistics','Retail','Automotive','IT-ITES','Hospitality']}/><div className="form-label language-box wide"><span>Languages known <em>*</em></span>{['Hindi','English','Rajasthani','Other'].map(language=><label key={language}><input type="checkbox" checked={data.languages.includes(language)} onChange={e=>set('languages',e.target.checked?[...data.languages,language]:data.languages.filter(x=>x!==language))}/>{language}</label>)}</div></div>}
        {step===4&&<div className="reg-fields"><Select name="trainingStatus" label="Training status" value={data.trainingStatus} set={set} options={['Not enrolled','Ongoing','Completed']}/>{data.trainingStatus!=='Not enrolled'&&<><Field name="trainingPartner" label="Training partner" value={data.trainingPartner} set={set} error={errors.trainingPartner}/><Field name="trainingCenter" label="Training center" value={data.trainingCenter} set={set} error={errors.trainingCenter}/><Field name="batchCode" label="Batch code" value={data.batchCode} set={set} error={errors.batchCode}/><Field name="batchEndDate" label="Batch end date" type="date" value={data.batchEndDate} set={set} error={errors.batchEndDate}/></>}<Field name="aadhaar" label="Aadhaar number" value={data.aadhaar} set={set} error={errors.aadhaar} optional hint="Optional; encrypted at rest and excluded from responses"/><File name="resume" label="Existing resume" accept=".pdf,.doc,.docx" setFiles={setFiles} hint="PDF or DOCX · maximum 5 MB"/><File name="certificate" label="Qualification / training certificate" accept=".pdf,.jpg,.jpeg,.png" setFiles={setFiles} hint="PDF or image · maximum 5 MB"/></div>}
        {step===5&&<div className="consent-review"><div className="review-summary"><h3>Candidate profile summary</h3><div><span>Name<b>{data.firstName} {data.lastName}</b></span><span>WhatsApp<b>{data.whatsapp}</b></span><span>Location<b>{data.currentLocation}, {data.district}</b></span><span>Job preference<b>{data.industry} · ₹{data.salary}</b></span><span>Training<b>{data.trainingStatus}</b></span><span>Available<b>{data.availability}</b></span></div></div><h3>Communication preferences</h3><div className="consent-channels">{[['callConsent','Phone calls'],['smsConsent','SMS alerts'],['whatsappConsent','WhatsApp messages'],['emailConsent','Email updates']].map(([key,label])=><label key={key}><span><ShieldCheck/></span><div><b>{label}</b><small>Jobs and interview updates</small></div><input type="checkbox" checked={data[key]} onChange={e=>set(key,e.target.checked)}/></label>)}</div><Legal checked={data.terms} onChange={v=>set('terms',v)} error={errors.terms}>I agree to the Terms & Conditions and candidate-job matching processing.</Legal><Legal checked={data.privacy} onChange={v=>set('privacy',v)} error={errors.privacy}>I accept the Privacy Policy and understand my data rights.</Legal><div className="consent-proof"><ShieldCheck/><p>Consent evidence stores notice version 1.0, timestamp, registration source and selected channels.</p></div></div>}
        {message&&<div className="reg-submit-error" role="alert">{message}</div>}
        <footer className="reg-footer"><button type="button" className="btn ghost" onClick={()=>step?setStep(x=>x-1):nav(-1)}><ArrowLeft/>{step?'Previous':'Cancel'}</button><div><button type="button" className="btn ghost" disabled={savingDraft} onClick={saveDraft}><Save/>{savingDraft?'Saving…':'Save draft'}</button><button type="button" className="btn primary" disabled={busy} onClick={step<5?advance:submit}>{busy?'Creating profile…':step===5?'Create candidate profile':'Continue'}{!busy&&<ArrowRight/>}</button></div></footer>
      </section></main>
  </div>;
}

function Field({name,label,value,set,error,type='text',optional=false,wide=false,hint,textarea=false}){return <label className={`form-label reg-field ${wide?'wide ':''}${error?'has-error':''}`}><span>{label}{!optional&&<em>*</em>}</span>{textarea?<textarea rows="3" value={value} onChange={e=>set(name,e.target.value)}/>:<input type={type} value={value} onChange={e=>set(name,e.target.value)}/>} {hint&&<small>{hint}</small>}{error&&<small className="reg-error">{error[0]}</small>}</label>}
function Select({name,label,value,set,error,options}){return <label className={`form-label reg-field ${error?'has-error':''}`}><span>{label}<em>*</em></span><select value={value} onChange={e=>set(name,e.target.value)}>{options.map(x=><option key={x} value={x}>{x||`Select ${label.toLowerCase()}`}</option>)}</select>{error&&<small className="reg-error">{error[0]}</small>}</label>}
function File({name,label,accept,setFiles,hint}){const[fileName,setFileName]=useState('');return <label className="form-label file-box"><Upload/><div><span>{label}</span><small>{fileName||hint}</small></div><b>Browse</b><input type="file" accept={accept} onChange={e=>{const file=e.target.files?.[0];setFileName(file?.name||'');setFiles(current=>({...current,[name]:file}))}}/></label>}
function Toggle({label,checked,onChange}){return <div className="location-permission wide"><ShieldCheck/><div><b>{label}</b><p>You can change this preference later.</p></div><label className="switch"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/></label></div>}
function Legal({checked,onChange,error,children}){return <><label className="legal-check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{children}</span></label>{error&&<small className="reg-error">{error[0]}</small>}</>}
