import React,{useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,BriefcaseBusiness,CalendarDays,Check,CheckCircle2,ChevronRight,Clock3,Heart,MapPin,Search,SlidersHorizontal,Trash2,Users,Wallet,X} from 'lucide-react';

export const initialInterests=[
  {id:1,title:'Machine Operator',location:'Jaipur, Rajasthan',salary:'₹14,000 – ₹18,000 / month',type:'Full time',openings:'12 openings',match:86,stage:'Interview scheduled',date:'16 Sep 2026',availability:'16 Sep · 11:30 AM',employer:'Astro Components',note:'Your interview is confirmed. Review the details and prepare for your meeting.'},
  {id:2,title:'CNC Trainee',location:'VKI, Jaipur',salary:'₹16,000 – ₹20,000 / month',type:'Full time',openings:'6 openings',match:82,stage:'Interest shared',date:'13 Sep 2026',availability:'Not selected',employer:'Shared after confirmation',note:'Your interest has been shared. Add your availability to help schedule an interview.'},
  {id:3,title:'Quality Inspector',location:'Sitapura, Jaipur',salary:'₹15,000 – ₹19,000 / month',type:'Full time',openings:'8 openings',match:78,stage:'Saved',date:'12 Sep 2026',availability:'Not selected',employer:'Shared after confirmation',note:'This opportunity is saved for you to review.'}
];
const options=['Tomorrow morning','Tomorrow afternoon','Within 3 days','Next week'];

export default function Candidate2Interests(){
  const [params,setParams]=useSearchParams();
  const [items,setItems]=useState(()=>{try{return JSON.parse(localStorage.getItem('candidate2-interests'))||initialInterests}catch{return initialInterests}});
  const [filter,setFilter]=useState('All interests'),[selected,setSelected]=useState(null),[slot,setSlot]=useState(''),[notice,setNotice]=useState('');
  const query=params.get('q')||'';
  const counts={all:items.length,interviews:items.filter(x=>x.stage==='Interview scheduled').length,waiting:items.filter(x=>x.stage==='Interest shared').length,saved:items.filter(x=>x.stage==='Saved').length};
  const visible=useMemo(()=>items.filter(x=>(filter==='All interests'||x.stage===filter)&&[x.title,x.location,x.stage].join(' ').toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  function update(next,msg){setItems(next);localStorage.setItem('candidate2-interests',JSON.stringify(next));setNotice(msg);setSelected(null);setSlot('')}
  function saveAvailability(){if(!slot)return;update(items.map(x=>x.id===selected.id?{...x,availability:slot,stage:x.stage==='Saved'?'Interest shared':x.stage}:x),'Interview availability saved')}
  function removeInterest(){update(items.filter(x=>x.id!==selected.id),'Interest removed')}
  return <div className="candidate2-interests">
    <div className="candidate2-breadcrumb"><Link to="/candidate2/interests">My career</Link><ChevronRight size={14}/><span>My interests</span></div>
    <section className="candidate2-hero"><div><span className="candidate2-eyebrow"><Heart size={15}/> YOUR OPPORTUNITIES</span><h1>My job interests</h1><p>Keep track of the jobs you like, share your availability, and stay ready for your next interview.</p><Link className="candidate2-hero-link" to="/candidate2/opportunities">Explore more jobs <ArrowRight size={17}/></Link></div><div className="candidate2-hero-art" aria-hidden="true"><div className="candidate2-art-card"><span><BriefcaseBusiness size={22}/></span><i/><i/><i/></div><div className="candidate2-art-check"><Check size={28}/></div></div></section>
    <section className="candidate2-summary" aria-label="Interest summary"><div><span className="blue"><Heart size={20}/></span><p>Jobs in your list<strong>{counts.all}</strong></p></div><div><span className="violet"><CalendarDays size={20}/></span><p>Interviews scheduled<strong>{counts.interviews}</strong></p></div><div><span className="amber"><Clock3 size={20}/></span><p>Awaiting response<strong>{counts.waiting}</strong></p></div><div><span className="green"><CheckCircle2 size={20}/></span><p>Saved to review<strong>{counts.saved}</strong></p></div></section>
    <section className="candidate2-list-section"><div className="candidate2-section-heading"><div><span>YOUR ACTIVITY</span><h2>Interested opportunities</h2><p>All the roles you have shown interest in, in one place.</p></div><Link to="/candidate2/opportunities">Browse jobs <ArrowRight size={16}/></Link></div>
      <div className="candidate2-toolbar"><div className="candidate2-tabs" role="tablist" aria-label="Filter interests">{['All interests','Interview scheduled','Interest shared','Saved'].map(t=><button key={t} type="button" role="tab" aria-selected={filter===t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t}<span>{t==='All interests'?counts.all:t==='Interview scheduled'?counts.interviews:t==='Interest shared'?counts.waiting:counts.saved}</span></button>)}</div><label className="candidate2-filter-search"><Search size={17}/><input aria-label="Filter interests" placeholder="Search roles or locations" value={query} onChange={e=>setParams(e.target.value?{q:e.target.value}:{})}/></label></div>
      {visible.length?<div className="candidate2-cards">{visible.map(job=><article className="candidate2-job" key={job.id}><div className="candidate2-job-top"><span className="candidate2-job-icon"><BriefcaseBusiness size={23}/></span><div className="candidate2-job-title"><h3>{job.title}</h3><p><MapPin size={15}/>{job.location}</p></div><span className={'candidate2-stage '+(job.stage==='Interview scheduled'?'scheduled':job.stage==='Saved'?'saved':'shared')}>{job.stage==='Interview scheduled'?<CalendarDays size={14}/>:job.stage==='Saved'?<Heart size={14}/>:<Clock3 size={14}/>} {job.stage}</span></div><div className="candidate2-job-facts"><span><Wallet size={16}/>{job.salary}</span><span><BriefcaseBusiness size={16}/>{job.type}</span><span><Users size={16}/>{job.openings}</span></div><div className="candidate2-job-bottom"><div className="candidate2-match"><b>{job.match}% match</b><span>Based on your profile</span></div><div className="candidate2-job-actions"><button type="button" className="candidate2-text-action" onClick={()=>{setSelected(job);setSlot(job.availability==='Not selected'?'':job.availability)}}>View details <ArrowRight size={16}/></button>{job.stage==='Interview scheduled'?<Link className="candidate2-solid-action" to="/candidate2/interviews">View interview <ArrowRight size={16}/></Link>:<button type="button" className="candidate2-solid-action" onClick={()=>{setSelected(job);setSlot(job.availability==='Not selected'?'':job.availability)}}>{job.stage==='Saved'?'Review interest':'Add availability'} <ArrowRight size={16}/></button>}</div></div></article>)}</div>:<div className="candidate2-empty"><SlidersHorizontal size={28}/><h3>No interests found</h3><p>Try another search or filter, or explore available jobs.</p><button onClick={()=>{setFilter('All interests');setParams({})}}>Clear filters</button></div>}
    </section>
    <div className="candidate2-help"><span><CheckCircle2 size={20}/></span><div><b>Your information stays protected</b><p>Employer details are shared after your interview is confirmed. You can manage your preferences at any time.</p></div><Link to="/candidate2/consent">Manage preferences <ArrowRight size={16}/></Link></div>
    {notice&&<div className="candidate2-notice" role="status">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {selected&&<div className="candidate2-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="candidate2-modal" role="dialog" aria-modal="true" aria-labelledby="candidate2-dialog-title"><button className="candidate2-modal-close" aria-label="Close details" onClick={()=>setSelected(null)}><X size={20}/></button><span className="candidate2-eyebrow">OPPORTUNITY DETAILS</span><h2 id="candidate2-dialog-title">{selected.title}</h2><p className="candidate2-modal-location"><MapPin size={16}/>{selected.location}</p><div className="candidate2-modal-facts"><div><small>Monthly salary</small><b>{selected.salary}</b></div><div><small>Openings</small><b>{selected.openings}</b></div><div><small>Employer</small><b>{selected.employer}</b></div><div><small>Interest added</small><b>{selected.date}</b></div></div><div className="candidate2-modal-status"><b>{selected.stage}</b><p>{selected.note}</p></div>{selected.stage==='Interview scheduled'?<Link className="candidate2-solid-action" to="/candidate2/interviews" onClick={()=>setSelected(null)}>Open interview details <ArrowRight size={16}/></Link>:<div className="candidate2-availability"><label htmlFor="candidate2-slot">Interview availability</label><select id="candidate2-slot" value={slot} onChange={e=>setSlot(e.target.value)}><option value="">Choose when you are available</option>{options.map(o=><option key={o}>{o}</option>)}</select><button className="candidate2-solid-action" disabled={!slot} onClick={saveAvailability}>Save availability <Check size={16}/></button></div>}<button className="candidate2-remove" onClick={removeInterest}><Trash2 size={16}/> Remove from my interests</button></section></div>}
  </div>
}
