import React,{useState}from'react';
import{useNavigate,useParams}from'react-router-dom';
import{CalendarDays,Users,UserCheck,BriefcaseBusiness,MapPin,ArrowLeft,ChevronRight,AlertTriangle}from'lucide-react';
import{PageHead,Stat,Status,Tabs}from'../../components/UI.jsx';

const rows=[
  {id:'1',name:'CNC Operator — B14',partner:'Rajasthan Skills Hub',location:'Jaipur',end:'22 Sep 2026',students:38,ready:31,matched:24,placed:18,status:'Placement ready'},
  {id:'2',name:'Warehouse Associate — B08',partner:'Udaan Training Foundation',location:'Ajmer',end:'25 Sep 2026',students:42,ready:36,matched:27,placed:16,status:'Matching'},
  {id:'3',name:'Retail Sales — B21',partner:'Future Skills Academy',location:'Kota',end:'02 Oct 2026',students:35,ready:24,matched:12,placed:8,status:'Needs attention'},
  {id:'4',name:'Machine Operator — B11',partner:'Pragati Kaushal Kendra',location:'Alwar',end:'06 Oct 2026',students:46,ready:39,matched:29,placed:21,status:'Matching'},
];

export default function Batches(){const nav=useNavigate(),{id}=useParams(),[tab,setTab]=useState('Upcoming');const batch=rows.find(x=>x.id===id);if(batch)return <><button className="back-link" onClick={()=>nav('/admin/batches')}><ArrowLeft/>Back to batches</button><PageHead kicker="BATCH READINESS" title={batch.name} sub={`${batch.partner} · ${batch.location} · completes ${batch.end}`}><button className="btn ghost" onClick={()=>nav('/admin/candidates')}>View students</button><button className="btn primary" onClick={()=>nav('/admin/jobs')}>Match with jobs</button></PageHead><div className="stat-grid"><Stat icon={Users} label="Enrolled students" value={batch.students} meta="2 profiles incomplete"/><Stat icon={UserCheck} label="Job ready" value={batch.ready} meta={`${Math.round(batch.ready/batch.students*100)}% readiness`} tone="green"/><Stat icon={BriefcaseBusiness} label="Matched" value={batch.matched} meta="Across 8 job requirements" tone="purple"/><Stat icon={UserCheck} label="Already placed" value={batch.placed} meta={`${Math.round(batch.placed/batch.students*100)}% placement rate`} tone="teal"/></div><div className="dashboard-grid batch-detail-grid"><section className="panel"><header><div><h3>Student placement readiness</h3><p>Actions to complete before batch closure</p></div></header><div className="panel-body"><div className="readiness-steps">{[['Profile & documents',34,38],['Assessment completed',32,38],['Job preference confirmed',31,38],['Matched to live jobs',24,38],['Interview scheduled',19,38]].map(x=><div key={x[0]}><span><b>{x[0]}</b><strong>{x[1]} / {x[2]}</strong></span><i><em style={{width:x[1]/x[2]*100+'%'}}/></i></div>)}</div></div></section><section className="panel"><header><div><h3>Immediate attention</h3><p>Exceptions blocking placement</p></div></header><div className="panel-body"><div className="attention-list"><button onClick={()=>nav('/admin/candidates')}><AlertTriangle/><span><b>4 incomplete profiles</b><small>Documents or preferences missing</small></span><ChevronRight/></button><button onClick={()=>nav('/admin/crm')}><AlertTriangle/><span><b>3 students unreachable</b><small>No response in last 7 days</small></span><ChevronRight/></button><button onClick={()=>nav('/admin/jobs')}><AlertTriangle/><span><b>7 students unmatched</b><small>No suitable active requirement</small></span><ChevronRight/></button></div></div></section></div></>;
return <><PageHead kicker="TRAINING SUPPLY" title="Batches & placement readiness" sub="Monitor every cohort from training completion through placement."><button className="btn ghost">Export</button></PageHead><div className="stat-grid"><Stat icon={CalendarDays} label="Active batches" value="64" meta="2,184 students"/><Stat icon={CalendarDays} label="Ending in 30 days" value="12" meta="438 students" tone="amber"/><Stat icon={UserCheck} label="Ready for matching" value="327" meta="74.7% of upcoming" tone="green"/><Stat icon={Users} label="Unplaced alumni" value="286" meta="Across 19 completed batches" tone="red"/></div><Tabs tabs={['Upcoming','Active','Completed','Needs attention']} active={tab} setActive={setTab}/><div className="data-card"><div className="table-scroll"><table className="data-table batches-table"><thead><tr><th>Batch</th><th>Training partner</th><th>Location</th><th>Completion</th><th>Students</th><th>Job ready</th><th>Matched</th><th>Placed</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>nav('/admin/batches/'+x.id)}><td><b>{x.name}</b><small>EXO-BAT-00{x.id}</small></td><td>{x.partner}</td><td><span className="table-location"><MapPin/>{x.location}</span></td><td>{x.end}</td><td>{x.students}</td><td>{x.ready}</td><td>{x.matched}</td><td>{x.placed}</td><td><Status tone={x.status==='Needs attention'?'high-risk':x.status==='Matching'?'joining-pending':'active'}>{x.status}</Status></td><td><ChevronRight/></td></tr>)}</tbody></table></div></div></>}
