import React,{useEffect,useState} from 'react';
import axios from 'axios';
import {Link} from 'react-router-dom';
import {ArrowLeft,Download,ArrowDownUp} from 'lucide-react';
import {PageHead,Status} from '../../components/UI.jsx';
import {exportCsv,sortRecords,statusLabels} from './employer-admin-utils.js';
import '../../data-tables.css';
import './employer-admin.css';
const monthNow=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
const initialFrom=()=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
const labelMonth=m=>new Date(`${m}-01T00:00:00`).toLocaleDateString('en-IN',{month:'short',year:'2-digit'});
function Bars({items,unit}) {const max=Math.max(1,...items.map(i=>i.value));return items.length?<div className="ea-bars">{items.map(i=><div className="ea-bar-row" key={i.label}><span>{i.label}</span><div><i style={{width:`${i.value/max*100}%`}}/></div><b>{i.value} <small>{unit}</small></b></div>)}</div>:<p className="ea-chart-empty">No activity in this period.</p>;}
function Trend({months}) {const max=Math.max(1,...months.flatMap(m=>[m.registrations,m.jobs,m.hires]));return <><div className="ea-legend"><span><i/>Registrations</span><span><i/>Published jobs</span><span><i/>Joined candidates</span></div><div className="ea-trend" role="img" aria-label="Monthly activity chart. Exact values appear in the monthly breakdown table.">{months.map(m=><div className="ea-month" key={m.month}><div className="ea-month-bars">{['registrations','jobs','hires'].map(k=><div key={k} className={`ea-trend-bar ${k}`} style={{height:`${m[k]/max*150}px`}} title={`${labelMonth(m.month)}: ${m[k]} ${k}`}><span>{m[k]}</span></div>)}</div><span>{labelMonth(m.month)}</span></div>)}</div></>;}
export default function EmployerStats() {
 const [filters,setFilters]=useState({from:initialFrom(),to:monthNow(),industry:'',state:'',status:''}),[options,setOptions]=useState([]),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[sort,setSort]=useState('hires'),[direction,setDirection]=useState('desc'),[query,setQuery]=useState(''),[limit,setLimit]=useState(20);
 useEffect(()=>{axios.get('/admin-api/employers').then(({data})=>setOptions([...data.filters.industries.map(industry=>({industry})),...data.filters.states.map(state=>({state}))])).catch(()=>{});},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');axios.get('/admin-api/employers/stats',{params:filters,signal:controller.signal}).then(({data})=>setData(data)).catch(e=>{if(e.code!=='ERR_CANCELED')setError(e.response?.status===403?'Your account needs employer viewing permission. Sign in with an authorized admin account.':Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'Statistics could not be loaded.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[filters]);
 const change=(key,value)=>setFilters(f=>({...f,[key]:value}));
 const performance=sortRecords((data?.performance||[]).filter(e=>[e.name,e.code].some(v=>String(v).toLowerCase().includes(query.trim().toLowerCase()))),sort,direction);
 const top=key=>sortRecords(data.performance,key,'desc').filter(e=>e[key]>0).slice(0,5).map(e=>({label:e.name,value:e[key]}));
 const sorting=key=>{setSort(key);setDirection(sort===key&&direction==='desc'?'asc':'desc');};
 return <div className="employer-admin"><PageHead title="Employer statistics" sub="Registrations, job publishing and confirmed joining outcomes."><Link className="btn ghost" to="/admin/employers"><ArrowLeft size={16}/>Employers</Link><button className="btn primary" disabled={loading||!!error||!data?.performance.length} onClick={()=>exportCsv(`employer-performance-${filters.from}-${filters.to}.csv`,[['Employer','name'],['Code','code'],['Industry','industry'],['State','state'],['Status','status'],['Published jobs','jobs'],['Openings','openings'],['Joined candidates','hires']],performance)}><Download size={16}/>Export performance</button></PageHead>
 <section className="ea-surface"><div className="ea-filters ea-stats-filters"><label>From month<input type="month" value={filters.from} max={filters.to} onChange={e=>{if(e.target.value)change('from',e.target.value);}}/></label><label>To month<input type="month" value={filters.to} min={filters.from} onChange={e=>{if(e.target.value)change('to',e.target.value);}}/></label>{['industry','state','status'].map(key=><label key={key}>{key==='status'?'Current status':key==='state'?'State':'Industry'}<select value={filters[key]} onChange={e=>change(key,e.target.value)}><option value="">All {key==='status'?'statuses':key==='state'?'states':'industries'}</option>{key==='status'?Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>):[...new Set(options.map(e=>e[key]).filter(Boolean))].sort().map(v=><option key={v}>{v}</option>)}</select></label>)}<div className="ea-presets"><button className="btn ghost" onClick={()=>setFilters({...filters,from:monthNow(),to:monthNow()})}>This month</button><button className="btn ghost" onClick={()=>setFilters({from:initialFrom(),to:monthNow(),industry:'',state:'',status:''})}>Reset</button></div></div></section>
 {loading?<div className="ea-empty" role="status">Loading statistics…</div>:error?<div className="ea-empty ea-error" role="alert">{error}<button className="btn ghost" onClick={()=>setFilters({...filters})}>Retry</button></div>:data&&<>
 <p className="ea-period">{labelMonth(data.from)} – {labelMonth(data.to)} · Select the same start and end month to view a single month.</p><div className="ea-metrics">{[['Total employers',data.summary.employers,'Registered by end of period'],['New employers',data.summary.new_employers,'Registered during period'],['Jobs published',data.summary.jobs,'First published during period'],['Candidates joined',data.summary.hires,`${data.summary.hiring_employers} employers recorded hires`]].map(([label,value,sub])=><article key={label}><span>{label}</span><strong>{value.toLocaleString('en-IN')}</strong><small>{sub}</small></article>)}</div>
 <div className="ea-charts"><section className="ea-surface ea-chart ea-chart-wide"><h2>Monthly activity</h2><p>Registrations, published jobs and actual joining outcomes.</p><Trend months={data.months}/></section><section className="ea-surface ea-chart"><h2>Profile status</h2><p>Current status of employers registered by period end.</p><Bars items={Object.entries(statusLabels).map(([k,label])=>({label,value:data.statuses[k]||0}))} unit="employers"/></section><section className="ea-surface ea-chart"><h2>Who hired most</h2><p>Top 5 by distinct candidates who joined in this period.</p><Bars items={top('hires')} unit="hires"/></section><section className="ea-surface ea-chart"><h2>Who posted most jobs</h2><p>Top 5 by jobs first published in this period.</p><Bars items={top('jobs')} unit="jobs"/></section><section className="ea-surface ea-chart"><h2>Employers by industry</h2><p>Largest industries within the selected filters.</p><Bars items={Object.entries(data.industries).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,8)} unit="employers"/></section></div>
 <section className="ea-surface"><div className="ea-table-caption"><div><h2>Employer performance</h2><span className="ea-muted">Sort columns to compare the complete filtered dataset.</span></div><label>Search employer<input value={query} onChange={e=>{setQuery(e.target.value);setLimit(20);}} placeholder="Name or employer code"/></label></div><div className="data-table ea-table"><table><thead><tr>{[['Employer','name'],['Industry','industry'],['Status','status'],['Published jobs','jobs'],['Openings','openings'],['Joined candidates','hires']].map(([label,key])=><th key={key} aria-sort={sort===key?(direction==='asc'?'ascending':'descending'):'none'}><button onClick={()=>sorting(key)}>{label}<ArrowDownUp size={13}/>{sort===key?(direction==='asc'?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{performance.slice(0,limit).map(e=><tr key={e.id}><td><Link className="table-record-link" to={`/admin/employers?review=${e.id}`}>{e.name}</Link><small>{e.code}</small></td><td>{e.industry||'Unspecified'}<small>{e.state||'State not provided'}</small></td><td><Status tone={e.status}>{statusLabels[e.status]||e.status}</Status></td><td>{e.jobs}</td><td>{e.openings}</td><td>{e.hires}</td></tr>)}{!performance.length&&<tr><td colSpan={6}>No employers match these filters.</td></tr>}</tbody></table></div><footer className="ea-pagination"><span>Showing {Math.min(limit,performance.length)} of {performance.length}</span>{limit<performance.length&&<button className="btn ghost" onClick={()=>setLimit(limit+20)}>Show 20 more</button>}</footer></section>
 <section className="ea-surface ea-monthly-table"><div className="ea-table-caption"><h2>Monthly breakdown</h2><button className="btn ghost" onClick={()=>exportCsv('employer-monthly-activity.csv',[['Month','month'],['New employers','registrations'],['Published jobs','jobs'],['Joined candidates','hires']],data.months)}><Download size={16}/>Export months</button></div><div className="data-table ea-table"><table><thead><tr><th>Month</th><th>New employers</th><th>Published jobs</th><th>Joined candidates</th></tr></thead><tbody>{data.months.map(m=><tr key={m.month}><td>{labelMonth(m.month)}</td><td>{m.registrations}</td><td>{m.jobs}</td><td>{m.hires}</td></tr>)}</tbody></table></div></section><p className="ea-footnote">Hires count distinct candidates per employer with a recorded joining date. Unpublished drafts are excluded; previously published jobs remain counted. Status and industry use current profile values. Undated employers appear in totals but not monthly registrations. Deleted employers, jobs and candidates are excluded.</p>
 </>}
 </div>;
}

