import React,{useEffect,useMemo,useState}from'react';
import axios from'axios';
import{Database,Users,ShieldCheck,MessageCircle,SlidersHorizontal,Plus,Save}from'lucide-react';
import{PageHead}from'../../components/UI';
import{useToast}from'../../App';

const types=[['qualification','Qualifications'],['state','States'],['district','Districts'],['experience_level','Experience levels'],['industry','Industries'],['language','Languages']];
const csrf=()=>({'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content});
const slugify=value=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

export default function Settings(){
  const toast=useToast(),[section,setSection]=useState('Master data'),[type,setType]=useState('qualification'),[records,setRecords]=useState({options:[],states:[],districts:[]}),[form,setForm]=useState({name:'',state_id:'',sort_order:0}),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const refresh=()=>axios.get('/admin-api/master-data').then(({data})=>setRecords(data)).catch(e=>setError(e.response?.data?.message||'Could not load master data. Sign in as an authorized admin.'));
  useEffect(()=>{refresh()},[]);
  const items=useMemo(()=>type==='state'?records.states:type==='district'?records.districts:records.options.filter(x=>x.type===type),[records,type]);
  const activeStates=records.states.filter(x=>x.is_active);
  const save=async()=>{if(!form.name.trim()){setError('Enter a name.');return}if(type==='district'&&!form.state_id){setError('Choose a state.');return}setBusy(true);setError('');try{await axios.post(`/admin-api/master-data/${type}`,{name:form.name.trim(),slug:slugify(form.name),sort_order:Number(form.sort_order)||0,...(type==='district'?{state_id:Number(form.state_id)}:{})},{headers:csrf()});setForm({name:'',state_id:'',sort_order:0});await refresh();toast('Master value saved')}catch(e){setError(e.response?.data?.message||'Could not save this value.')}finally{setBusy(false)}};
  const update=async(id,values)=>{setBusy(true);setError('');try{await axios.patch(`/admin-api/master-data/${type}/${id}`,values,{headers:csrf()});setEdit(null);await refresh();toast('Master value updated')}catch(e){setError(e.response?.data?.message||'Could not update this value.')}finally{setBusy(false)}};
  const tabs=[[Database,'Master data'],[Users,'Users & roles'],[MessageCircle,'Communication'],[SlidersHorizontal,'Workflow rules'],[ShieldCheck,'Privacy & security']];
  return <><PageHead title="Masters & settings" sub="Manage the values shown in candidate registration dropdowns."/><div className="settings-cards">{tabs.map(([Icon,label])=><button key={label} className={section===label?'active':''} onClick={()=>setSection(label)}><Icon/><b>{label}</b></button>)}</div>{section==='Master data'?<div className="data-card" style={{padding:24}}><div className="settings-head"><div><h3>Candidate form master data</h3><p>Deactivate old values to preserve existing candidate references. Slugs stay fixed after creation.</p></div></div><label className="field-label" style={{maxWidth:300}}>Dataset<select value={type} onChange={e=>{setType(e.target.value);setEdit(null);setError('')}}>{types.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="form-grid" style={{margin:'18px 0'}}><label className="field-label">Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="New option name"/></label>{type==='district'&&<label className="field-label">State<select value={form.state_id} onChange={e=>setForm({...form,state_id:e.target.value})}><option value="">Select state</option>{activeStates.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<label className="field-label">Sort order<input type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label></div><button className="btn primary" disabled={busy} onClick={save}><Plus/>Add value</button>{error&&<p role="alert" className="reg-submit-error">{error}</p>}<div className="table-wrap" style={{overflowX:'auto',marginTop:24}}><table className="data-table"><thead><tr><th>Name</th><th>Slug</th>{type==='district'&&<th>State</th>}<th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{edit?.id===x.id?<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/>:<b>{x.name}</b>}</td><td><code>{x.slug}</code></td>{type==='district'&&<td>{records.states.find(s=>s.id===x.state_id)?.name||'Unknown'}</td>}<td>{edit?.id===x.id?<input type="number" min="0" value={edit.sort_order} onChange={e=>setEdit({...edit,sort_order:e.target.value})} style={{width:75}}/>:x.sort_order}</td><td>{x.is_active?'Active':'Inactive'}</td><td>{edit?.id===x.id?<button className="btn ghost" disabled={busy} onClick={()=>update(x.id,{name:edit.name,sort_order:Number(edit.sort_order)||0})}><Save/>Save</button>:<button className="btn ghost" onClick={()=>setEdit({id:x.id,name:x.name,sort_order:x.sort_order})}>Edit</button>} <button className="btn ghost" disabled={busy} onClick={()=>update(x.id,{is_active:!Boolean(x.is_active)})}>{x.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></div>:<div className="data-card" style={{padding:24}}><h3>{section}</h3><p>This settings area is not connected to the master data API yet.</p></div>}</>;
}
